export const uiIcons = {
	emotion: '/static/images/情绪.png',
	female: '/static/images/女.png',
	endurance: '/static/images/续航.png',
	hourglass: '/static/images/沙漏.png',
	location: '/static/images/位置.png',
	vote: '/static/images/投票.png',
	more: '/static/images/更多.png',
	back: '/static/images/返回.png',
	settings: '/static/images/设置.png',
	close: '/static/images/关闭.png',
	filter: '/static/images/筛选.png',
	search: '/static/images/搜索.png',
	throw: '/static/images/投掷.png',
	throwActive: '/static/images/投掷选中.png',
	home: '/static/images/首页.png',
	homeActive: '/static/images/首页选中.png',
	discover: '/static/images/雷达.png',
	discoverActive: '/static/images/雷达选中.png',
	trending: '/static/images/热门.png',
	trendingActive: '/static/images/热门选中.png',
}
