/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'comment-manage',
    path: '/comment-manage',
    component: 'layout.base$view.comment-manage',
    meta: {
      title: 'comment-manage',
      i18nKey: 'route.comment-manage',
      icon: 'mdi:comment-text-multiple-outline',
      order: 3
    }
  },
  {
    name: 'expire-manage',
    path: '/expire-manage',
    component: 'layout.base$view.expire-manage',
    meta: {
      title: 'expire-manage',
      i18nKey: 'route.expire-manage',
      icon: 'mdi:timer-sand',
      order: 6
    }
  },
  {
    name: 'headline-manage',
    path: '/headline-manage',
    component: 'layout.base$view.headline-manage',
    meta: {
      title: 'headline-manage',
      i18nKey: 'route.headline-manage',
      icon: 'mdi:text-box-multiple-outline',
      order: 7
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'location-manage',
    path: '/location-manage',
    component: 'layout.base$view.location-manage',
    meta: {
      title: 'location-manage',
      i18nKey: 'route.location-manage',
      icon: 'mdi:map-marker-radius-outline',
      order: 5
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'mood-manage',
    path: '/mood-manage',
    component: 'layout.base$view.mood-manage',
    meta: {
      title: 'mood-manage',
      i18nKey: 'route.mood-manage',
      icon: 'mdi:emoticon-outline',
      order: 4
    }
  },
  {
    name: 'plane-manage',
    path: '/plane-manage',
    component: 'layout.base$view.plane-manage',
    meta: {
      title: 'plane-manage',
      i18nKey: 'route.plane-manage'
    }
  },
  {
    name: 'report-manage',
    path: '/report-manage',
    component: 'layout.base$view.report-manage',
    meta: {
      title: 'report-manage',
      i18nKey: 'route.report-manage',
      icon: 'mdi:flag',
      order: 8
    }
  },
  {
    name: 'user-manage',
    path: '/user-manage',
    component: 'layout.base$view.user-manage',
    meta: {
      title: 'user-manage',
      i18nKey: 'route.user-manage',
      icon: 'mdi:account-group',
      order: 9
    }
  }
];
